site_name: oysh
site_url: https://noahhhx.github.io/oysh/
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.tracking

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Core:
      - Introduction: core/introduction.md
      - Usage: core/usage.md
      - Auth: core/auth.md
      - Command Frameworks: core/command-framework.md